# Sample CI/CD pipeline for Martini

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deployment"
  deployment:
    environment: prod
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checkout the git branch
      - uses: actions/checkout@v2
      
      # Zip the package we want to deploy
      - name: Zip Martini package
        run: |
          cd packages
          zip -qr ../demo-api-tasks.zip demo-api-tasks/*
      
      # Deploy the package to a remote Martini runtime server using the REST API
      - name: Deploy to server
        env:
          USERNAME: ${{ secrets.TORO_ACCOUNT_USERNAME }}
          PASSWORD: ${{ secrets.TORO_ACCOUNT_PASSWORD }}
        run: |
          # Base url of the server we'll deploy to
          server_url=https://toro277.us-east.toroserver.com
        
          # Retrieve the access token
          access_token=$(curl -X POST --http1.1 \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=password&username=$USERNAME&password=$PASSWORD&client_id=TOROMartini&client_secret=TOROMartini" \
          "${server_url}/oauth/token" | jq -r .access_token)
          
          # Upload the Martini package zip file
          curl -X POST --http1.1 \
          -F file=@demo-api-tasks.zip \
          -H "Authorization: Bearer ${access_token}" \
          "${server_url}/esbapi/packages/upload?stateOnCreate=STARTED&replaceExisting=true"
      
      # This step is optional, uploads the Martini package zip file so it can be manually checked
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: demo-api-tasks.zip
          path: demo-api-tasks.zip
          if-no-files-found: error
